CREATE TABLE IF NOT EXISTS COMPANY (
    ID SERIAL PRIMARY KEY,
    CPF CHAR(14) UNIQUE,
    CNPJ CHAR(18) UNIQUE,
    TYPE CHAR(2) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    CEP CHAR(9) NOT NULL,
    EMAIL VARCHAR(255),
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS PARTNERSHIP (
    ID SERIAL PRIMARY KEY,
    COMPANY_ID BIGINT REFERENCES COMPANY(ID) NOT NULL,
    SUPPLIER_ID BIGINT REFERENCES COMPANY(ID) NOT NULL,

    CONSTRAINT rel_identifier UNIQUE(COMPANY_ID, SUPPLIER_ID)
);


ALTER TABLE PARTNERSHIP
     ADD CONSTRAINT diff_value_constraint CHECK (
         (COMPANY_ID) != (SUPPLIER_ID)
     );

